[project]
name = "ComfyUI_Sora"
description = "A professional collection of ComfyUI Sora video generation nodes"
version = "1.6.0"
license = {file = "LICENSE"}
dependencies = []

[project.urls]
Repository = "https://github.com/xuchenxu168/ComfyUI_Sora"
"Bug Tracker" = "https://github.com/xuchenxu168/ComfyUI_Sora/issues"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "xuchenxu168"
DisplayName = "ComfyUI_Sora"
Icon = ""
includes = []
